#PROJECT_PATH="/workspace2/model/MarkitS_"
PROJECT_PATH="/workspace/MarkitS_test/MarkitS"
YOLO_PATH="${PROJECT_PATH}/yolov7"
WEIGHTS_PATH="${PROJECT_PATH}/weights"
export PYTHONPATH="${PROJECT_PATH}/TexTeller/src"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:=0}"